from sqlalchemy import Column, Integer, String, JSON, ARRAY, Numeric, TIMESTAMP, Boolean
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Capsules(Base):
	__tablename__ = "capsules"
	reuse_count = Column(Numeric)
	water_landings = Column(Numeric)
	land_landings = Column(Numeric)
	last_update = Column(String)
	launches = Column(ARRAY(String))
	serial = Column(String)
	status = Column(String)
	type = Column(String)
	id = Column(String,primary_key=True)

class Cores(Base):
	__tablename__ = "cores"
	block = Column(Numeric)
	reuse_count = Column(Numeric)
	rtls_attempts = Column(Numeric)
	rtls_landings = Column(Numeric)
	asds_attempts = Column(Numeric)
	asds_landings = Column(Numeric)
	last_update = Column(String)
	launches = Column(ARRAY(String))
	serial = Column(String)
	status = Column(String)
	id = Column(String,primary_key=True)

class Crew(Base):
	__tablename__ = "crew"
	name = Column(String)
	agency = Column(String)
	image = Column(String)
	wikipedia = Column(String)
	launches = Column(ARRAY(String))
	status = Column(String)
	id = Column(String,primary_key=True)

class Landpads(Base):
	__tablename__ = "landpads"
	images = Column(JSON)
	name = Column(String)
	full_name = Column(String)
	status = Column(String)
	type = Column(String)
	locality = Column(String)
	region = Column(String)
	latitude = Column(Numeric)
	longitude = Column(Numeric)
	landing_attempts = Column(Numeric)
	landing_successes = Column(Numeric)
	wikipedia = Column(String)
	details = Column(String)
	launches = Column(ARRAY(String))
	id = Column(String,primary_key=True)

class Launches(Base):
	__tablename__ = "launches"
	fairings = Column(JSON)
	links = Column(JSON)
	static_fire_date_utc = Column(TIMESTAMP)
	static_fire_date_unix = Column(Numeric)
	net = Column(Boolean)
	window = Column(Numeric)
	rocket = Column(String)
	success = Column(Boolean)
	failures = Column(ARRAY(JSON))
	details = Column(String)
	crew = Column(ARRAY(String))
	ships = Column(ARRAY(String))
	capsules = Column(ARRAY(String))
	payloads = Column(ARRAY(String))
	launchpad = Column(String)
	flight_number = Column(Numeric)
	name = Column(String)
	date_utc = Column(TIMESTAMP)
	date_unix = Column(Numeric)
	date_local = Column(TIMESTAMP)
	date_precision = Column(String)
	upcoming = Column(Boolean)
	cores = Column(ARRAY(JSON))
	id = Column(String,primary_key=True)

class Launchpads(Base):
	__tablename__ = "launchpads"
	images = Column(JSON)
	name = Column(String)
	full_name = Column(String)
	locality = Column(String)
	region = Column(String)
	latitude = Column(Numeric)
	longitude = Column(Numeric)
	launch_attempts = Column(Numeric)
	launch_successes = Column(Numeric)
	rockets = Column(ARRAY(String))
	timezone = Column(String)
	launches = Column(ARRAY(String))
	status = Column(String)
	details = Column(String)
	id = Column(String,primary_key=True)

class Payloads(Base):
	__tablename__ = "payloads"
	dragon = Column(JSON)
	name = Column(String)
	type = Column(String)
	reused = Column(Boolean)
	launch = Column(String)
	customers = Column(ARRAY(String))
	norad_ids = Column(ARRAY(Integer))
	nationalities = Column(ARRAY(String))
	manufacturers = Column(ARRAY(String))
	mass_kg = Column(Numeric)
	mass_lbs = Column(Numeric)
	orbit = Column(String)
	reference_system = Column(String)
	regime = Column(String)
	longitude = Column(Numeric)
	semi_major_axis_km = Column(Numeric)
	eccentricity = Column(Numeric)
	periapsis_km = Column(Numeric)
	apoapsis_km = Column(Numeric)
	inclination_deg = Column(Numeric)
	period_min = Column(Numeric)
	lifespan_years = Column(Numeric)
	epoch = Column(TIMESTAMP)
	mean_motion = Column(Numeric)
	raan = Column(Numeric)
	arg_of_pericenter = Column(Numeric)
	mean_anomaly = Column(Numeric)
	id = Column(String,primary_key=True)

class Rockets(Base):
	__tablename__ = "rockets"
	height = Column(JSON)
	diameter = Column(JSON)
	mass = Column(JSON)
	first_stage = Column(JSON)
	second_stage = Column(JSON)
	engines = Column(JSON)
	landing_legs = Column(JSON)
	payload_weights = Column(ARRAY(JSON))
	flickr_images = Column(ARRAY(String))
	name = Column(String)
	type = Column(String)
	active = Column(Boolean)
	stages = Column(Numeric)
	boosters = Column(Numeric)
	cost_per_launch = Column(Numeric)
	success_rate_pct = Column(Numeric)
	first_flight = Column(TIMESTAMP)
	country = Column(String)
	company = Column(String)
	wikipedia = Column(String)
	description = Column(String)
	id = Column(String,primary_key=True)

class Ships(Base):
	__tablename__ = "ships"
	legacy_id = Column(String)
	model = Column(String)
	type = Column(String)
	roles = Column(ARRAY(String))
	imo = Column(Numeric)
	mmsi = Column(Numeric)
	abs = Column(Numeric)
	ship_class = Column(Numeric)
	mass_kg = Column(Numeric)
	mass_lbs = Column(Numeric)
	year_built = Column(Numeric)
	home_port = Column(String)
	status = Column(String)
	speed_kn = Column(Numeric)
	course_deg = Column(Numeric)
	latitude = Column(Numeric)
	longitude = Column(Numeric)
	link = Column(String)
	image = Column(String)
	name = Column(String)
	active = Column(Boolean)
	launches = Column(ARRAY(String))
	id = Column(String,primary_key=True)

class Starlink(Base):
	__tablename__ = "starlink"
	spaceTrack = Column(JSON)
	launch = Column(String)
	version = Column(String)
	height_km = Column(Numeric)
	latitude = Column(Numeric)
	longitude = Column(Numeric)
	velocity_kms = Column(Numeric)
	id = Column(String,primary_key=True)


